Transposition (Swapping Rows & Columns)

In [1]:
#For a 2D Matrix
import numpy as np

# Creating a 2D matrix
matrix_2d = np.array([[1, 2, 3], 
                       [4, 5, 6]])

# Transpose
transpose_2d = matrix_2d.T

print("Original 2D Matrix:\n", matrix_2d)
print("Transposed 2D Matrix:\n", transpose_2d)


The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Original 2D Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed 2D Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [2]:
#For a 3D Matrix:
matrix_3d = np.array([[[1, 2], [3, 4]], 
                       [[5, 6], [7, 8]]])

transpose_3d = np.transpose(matrix_3d, (0, 2, 1))

print("Original 3D Matrix:\n", matrix_3d)
print("Transposed 3D Matrix:\n", transpose_3d)


Original 3D Matrix:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Transposed 3D Matrix:
 [[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


# Rotation